apiVersion: v1
kind: Service
metadata:
  namespace: dynatrace-test
  name: db-postgres-service
spec:
  selector:
    app: db-postgres
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 30000!
      nodePort: 30000
      port: 5432
      targetPort: db-socket-port

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-deployment
  namespace: dynatrace-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: db-postgres
          image: postgres:12-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - name: db-socket-port
              containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  namespace: dynatrace-test
  name: rabbit-service
spec:
  selector:
    app: rabbit
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 3101!
      nodePort: 31000
      port: 15672
      targetPort: rabbit-ui-port
    - name: rabbit-stomp
      protocol: TCP
      port: 61613
      targetPort: rabbit-stomp
    - name: rabbit-pika
      protocol: TCP
      port: 5672
      targetPort: rabbit-pika

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dynatrace-test
  name: rabbit-configmap
data:
  "rabbitmq.conf": |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
  "enabled_plugins": |
    [rabbitmq_management,rabbitmq_stomp].

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-deployment
  namespace: dynatrace-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: rabbit-configmap
      containers:
        - name: rabbit
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          env:
            - name: STOMP_SERVER_USER
              value: guest
            - name: STOMP_SERVER_PASSWORD
              value: guest
          ports:
            - name: rabbit-ui-port
              containerPort: 15672
            - name: rabbit-pika
              containerPort: 5672
            - name: rabbit-stomp
              containerPort: 61613
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq/
              readOnly: true