apiVersion: v1
data:
  DB_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  STOMP_SERVER_PASSWORD: Z3Vlc3Q=
  STOMP_SERVER_USER: Z3Vlc3Q=
kind: Secret
metadata:
  name: django-template-secret
  namespace: dynatrace-test
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dynatrace-test
  name: django-template-configmap
data:
  ##########
  # Django
  DJANGO_HOST: "0.0.0.0"
  DJANGO_PORT: "8080"
  DJANGO_BIND_ADDRESS: "0.0.0.0"
  DJANGO_BIND_PORT: "8080"
  DJANGO_SETTINGS_MODULE: "django_template.settings"
  CSRF_COOKIE_SECURE: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_TRUSTED_ORIGINS: "http://localhost:8080"
  DJANGO_SECRET_KEY: "3123123213123"

  ##########
  # Logs
  DJANGO_DEBUG: "False"
  DJANGO_REQUEST_LOG_LEVEL: CRITICAL
  STOMP_LOG_LEVEL: WARNING
  DJANGO_DB_BACKENDS_LOG_LEVEL: INFO
  DJANGO_LOG_LEVEL: INFO
  ROOT_LOG_LEVEL: INFO
  PROJECT_LOG_LEVEL: INFO
  GUNICORN_LOG_LEVEL: DEBUG


  ##########
  # DYNATRACE
  AUTOWRAPT_BOOTSTRAP: "autodynatrace"
  AUTODYNATRACE_FORKABLE: "True"
  AUTODYNATRACE_CAPTURE_HEADERS: "True"
  AUTODYNATRACE_LOG_LEVEL: DEBUG
  DT_LOGLEVELCON: FINEST
  DT_LOGLEVELSDK: FINEST
  DT_LOGLEVELFILE: FINEST
  
  ##########
  # Data Base
  DB_ENGINE: django.db.backends.postgresql
  DB_CONN_MAX_AGE: "15"
  DB_DATABASE: "postgres"
  DB_HOST: db-postgres-service.dynatrace-test.svc.cluster.local
  DB_PORT: "5432"

  #########
  # Python in Docker
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"

  #########
  # ActiveMQ
  STOMP_LISTENER_CLIENT_ID: django_template_listener
  STOMP_SERVER_HOST: rabbit-service.dynatrace-test.svc.cluster.local
  STOMP_SERVER_VHOST: "/"
  STOMP_USE_SSL: "False"
  CREATE_AUDIT_ACTION_DESTINATION: /queue/create-audit-action
  STOMP_SERVER_PORT_PIKA: "5672"
  STOMP_SERVER_PORT: "61613"
  
  #########
  # GUNICORN
  GUNICORN_KEEPALIVE: "20"
  GUNICORN_MAX_REQUESTS: "1000"
  GUNICORN_MAX_REQUESTS_JITTER: "50"
  GUNICORN_WORKERS: "2"

  ENDPOINT_TO_PING_USER_ID: "http://django-template-service:8080/api/v1/users/ping/"