# Generated by Django 4.0.3 on 2022-03-03 17:19

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("user_id", models.CharField(max_length=128)),
                ("action", models.CharField(max_length=128)),
                ("success", models.BooleanField()),
                ("ip_address", models.GenericIPAddressField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
