# Generated by Django 4.0.4 on 2022-05-24 16:54

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttributes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("full_name", models.CharField(blank=True, max_length=70, null=True, verbose_name="User Full Name")),
                ("given_name", models.CharField(blank=True, max_length=35, null=True, verbose_name="Given Name")),
                ("family_name", models.CharField(blank=True, max_length=35, null=True, verbose_name="Family Name")),
                ("user_metadata", models.JSONField(default=dict, null=True, verbose_name="User data")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
