kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
    extraPortMappings:
      - containerPort: 32000
        # Django web server
        hostPort: 8080
        listenAddress: "127.0.0.1"
      - containerPort: 30000
        # postgres
        hostPort: 5432
        listenAddress: "127.0.0.1"
      - containerPort: 31000
        # RabbitMQ admin
        hostPort: 15672
        listenAddress: "127.0.0.1"
  - role: worker
    image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e